version: '2'
services:

    web:
      image: quay.io/abretaud/bbric-archive:master
      links:
        - db:postgres
        - elasticsearch:elasticsearch
      environment:
        - ARCHIVE_HTTP_HOST=https://localhost:5000/
        - ARCHIVE_HTTP_ROOT=archive
        - ARCHIVE_TITLE=Archive
        - ARCHIVE_FTP=your.ftp.site
#        - ARCHIVE_HTTP_HOST=https://bipaa.genouest.org/
#        - ARCHIVE_HTTP_ROOT=archive
#        - ARCHIVE_TITLE=BIPAA Archive
#        - ARCHIVE_FTP=bipaa-galaxy.genouest.org
#        - ARCHIVE_EXT_FTP=1
#        - ARCHIVE_CLIENT_MOUNTPOINT=/data/store
#        - ARCHIVE_ADMINS=someone@example.org,somebody@example.org
      volumes:
        - /data

    db:
      image: postgres:9.4
      environment:
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/9.4/
      volumes:
        - /var/lib/postgresql/9.4/

    elasticsearch:
      image: elasticsearch:5.1
      volumes:
        - /usr/share/elasticsearch/data
      environment:
        ES_JAVA_OPTS: "-Xms150m -Xmx150m"

    shibboleth:
        image: unicon/shibboleth-sp:3.0.4
        ports:
          - "5000:443"
        volumes:
          - ./shibboleth/sp-cert.pem:/etc/shibboleth/sp-cert.pem:ro
          - ./shibboleth/sp-key.pem:/etc/shibboleth/sp-key.pem:ro
          - ./shibboleth/metadata-federation-renater.crt:/etc/shibboleth/metadata-federation-renater.crt:ro
          - ./shibboleth/renater-metadata-signing-cert-2016.pem:/etc/shibboleth/renater-metadata-signing-cert-2016.pem:ro
          - ./shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro
          - ./shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro
          - ./shibboleth/attribute-policy.xml:/etc/shibboleth/attribute-policy.xml:ro
          - ./shibboleth/httpd_shib.conf:/etc/httpd/conf.d/shib.conf:ro
